-- ============================================================
-- Script: functions.sql
-- Purpose: Reusable scalar functions
-- ============================================================
USE retail_enterprise_db;

DELIMITER $$

-- Calculate a discounted price given a base price and discount percent
DROP FUNCTION IF EXISTS fn_calculate_discount $$
CREATE FUNCTION fn_calculate_discount(p_price DECIMAL(10,2), p_discount_pct DECIMAL(5,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    IF p_discount_pct IS NULL OR p_discount_pct < 0 THEN
        RETURN p_price;
    END IF;
    RETURN ROUND(p_price * (1 - p_discount_pct / 100), 2);
END $$

-- Total revenue generated by a single product (from order_items, excluding cancelled orders)
DROP FUNCTION IF EXISTS fn_product_revenue $$
CREATE FUNCTION fn_product_revenue(p_product_id INT)
RETURNS DECIMAL(14,2)
READS SQL DATA
DETERMINISTIC
BEGIN
    DECLARE v_revenue DECIMAL(14,2);
    SELECT COALESCE(SUM(oi.line_total), 0) INTO v_revenue
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    WHERE oi.product_id = p_product_id
      AND o.order_status NOT IN ('Cancelled');
    RETURN v_revenue;
END $$

-- Customer lifetime value = sum of total_amount across non-cancelled orders
DROP FUNCTION IF EXISTS fn_customer_lifetime_value $$
CREATE FUNCTION fn_customer_lifetime_value(p_customer_id INT)
RETURNS DECIMAL(14,2)
READS SQL DATA
DETERMINISTIC
BEGIN
    DECLARE v_clv DECIMAL(14,2);
    SELECT COALESCE(SUM(total_amount), 0) INTO v_clv
    FROM orders
    WHERE customer_id = p_customer_id
      AND order_status NOT IN ('Cancelled');
    RETURN v_clv;
END $$

-- Age in years from a date of birth (used for demographic analytics)
DROP FUNCTION IF EXISTS fn_age_years $$
CREATE FUNCTION fn_age_years(p_dob DATE)
RETURNS INT
DETERMINISTIC
BEGIN
    IF p_dob IS NULL THEN
        RETURN NULL;
    END IF;
    RETURN TIMESTAMPDIFF(YEAR, p_dob, CURDATE());
END $$

DELIMITER ;
